create table
  public.admin (
    id bigint generated by default as identity,
    username character varying null,
    password character varying null,
    created_at timestamp with time zone null default now(),
    name character varying null,
    type character varying null,
    constraint admin_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.album (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name character varying null,
    cover character varying null,
    updated_at timestamp without time zone null default now(),
    artists_id bigint null,
    constraint album_pkey primary key (id),
    constraint album_artists_id_fkey foreign key (artists_id) references artists (id)
  ) tablespace pg_default;

create table
  public.artists (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name character varying not null,
    cover_url character varying null,
    genre_id bigint null,
    constraint artists_pkey primary key (id),
    constraint artists_genre_id_fkey foreign key (genre_id) references genre (id)
  ) tablespace pg_default;

create table
  public.genre (
    id bigint generated by default as identity,
    name character varying null,
    created_at timestamp with time zone null default now(),
    constraint genre_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.playlist (
    id bigint generated by default as identity,
    name character varying null,
    created_at timestamp with time zone null default now(),
    constraint playlist_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.playlist_song (
    id bigint generated by default as identity,
    playlist_id bigint null,
    song_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint playlist_song_pkey primary key (id),
    constraint playlist_song_playlist_id_fkey foreign key (playlist_id) references playlist (id),
    constraint playlist_song_song_id_fkey foreign key (song_id) references songs (id)
  ) tablespace pg_default;

create table
  public.playlist_user (
    id bigint generated by default as identity,
    user_id bigint null,
    name character varying null,
    created_at timestamp with time zone null default now(),
    constraint playlist_user_pkey primary key (id),
    constraint playlist_user_user_id_fkey foreign key (user_id) references admin (id)
  ) tablespace pg_default;

create table
  public.playlist_user_song (
    id bigint generated by default as identity,
    playlist_user_id bigint null,
    song_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint playlist_user_song_pkey primary key (id),
    constraint playlist_user_song_playlist_user_id_fkey foreign key (playlist_user_id) references playlist_user (id),
    constraint playlist_user_song_song_id_fkey foreign key (song_id) references songs (id)
  ) tablespace pg_default;

create table
  public.songs (
    id bigint generated by default as identity,
    name character varying not null,
    youtube_url character varying null,
    cover_url character varying null,
    artist_id bigint not null,
    created_at timestamp with time zone null default now(),
    album_id bigint null,
    preview_url character varying null,
    constraint songs_pkey primary key (id),
    constraint songs_album_id_fkey foreign key (album_id) references album (id),
    constraint songs_artist_id_fkey foreign key (artist_id) references artists (id)
  ) tablespace pg_default;